<?php
/**
 * Created by PhpStorm.
 * User: dlepera
 * Date: 11/02/16
 * Time: 17:53
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if
?>

<html>
<head>
    <base href="<?php echo $params['base-html']; ?>"/>
    <title><?php echo "{$params['tag-title']} | {$params['config-aplicativo']['nome']}"; ?></title>

    [DLX-HEAD/]
    [DLX-ESTILOS/]
</head>

<body>

<section class="dlx-conteudo">
    <h1 class="titulo-h1"><?php echo $params['html:titulo-pagina']; ?></h1>

    [DLX-MENSAGENS-USUARIO/]
    [DLX-CONTEUDO/]
</section>

[DLX-SCRIPTS/]

</body>
</html>
