<?php
/**
 * framework-dlx
 * @version: v1.17.08
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\Sessao;
use DLX\Ajudantes\Visao as AjdVisao;

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if
?>

<html>
<head>
    <base href="<?php echo $params['conf:base-html']; ?>"/>
    <title><?php echo "{$params['tag-title']} | {$params['config-aplicativo']['nome']}"; ?></title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?php echo "{$params['diretorio-relativo']}{$params['config-aplicativo']['favicon']}" ?>"/>
    
    [DLX-HEAD/]
    [DLX-ARQUIVOS-CSS/]
    [DLX-ESTILOS/]
</head>

<body>
<header class="dlx-topo">
    <a href="" class="logo-site"><?php echo $params['config-aplicativo']['nome']; ?></a>

    [DLX-TOPO/]
</header>

<nav class="dlx-menu">
    [DLX-MENU/]
</nav>

<section class="dlx-conteudo">
    <h1 class="titulo-h1"><?php echo $params['html:titulo-pagina']; ?></h1>

    [DLX-MENSAGENS-USUARIO/]
    [DLX-CONTEUDO/]
</section>

<footer class="dlx-rodape">
    [DLX-RODAPE/]
</footer>

[DLX-ARQUIVOS-JS/]
[DLX-SCRIPTS/]

</body>
</html>
